matrix:
  include:
    - os: linux
      language: python

services:
  - xvfb

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

install:
  - pip install flake8==3.5
  - sh travis.sh bootstrap

script:
  - flake8 --max-line-length=150
  - sh travis.sh run_tests

